### ISSUE TITLE
No package matching '' is available

### ISSUE THREAD

**Issue by mvsantoss** [debops/ansible-php#17] opened 2016-10-26 18:12 UTC
Hi, found an error using in Ubuntu 14.04:

`failed: [trusty] (item=[u'', u'php7.0-cli', u'php7.0-fpm', u'php7.0', u'php7.0-curl', u'php7.0-gd', u'php7.0-mcrypt']) => {"failed": true, "item": ["", "php7.0-cli", "php7.0-fpm", "php7.0", "php7.0-curl", "php7.0-gd", "php7.0-mcrypt"], "msg": "No package matching '' is available"}`

Debugging the variable `php__register_filtered_packages` there is an empty line:

`ok: [trusty] => {
    "php__register_filtered_packages": {
        "changed": false, 
        "rc": 0, 
        "stderr": "", 
        "stdout": "\r\nphp7.0-cli\r\nphp7.0-fpm\r\nphp7.0\r\nphp7.0-curl\r\nphp7.0-gd\r\nphp7.0-mcrypt\r\n", 
        "stdout_lines": [
            "", 
            "php7.0-cli", 
            "php7.0-fpm", 
            "php7.0", 
            "php7.0-curl", 
            "php7.0-gd", 
            "php7.0-mcrypt"
        ]
    }
}
`

Any ideas how to handle this?

**Comment by drybjed** [comment] 2016-10-26 18:45
Add `debug` tasks to show all variables from [here](https://github.com/debops/ansible-php/blob/master/tasks/main.yml#L10) and show the output. I want to know what package might cause this.

After that the script should be fixed to not output empty list elements.

**Comment by mvsantoss** [comment] 2016-10-26 20:46
Here are the results:
`TASK [debops.php : debug] ******************************************************
ok: [server] => {
    "php__server_api_packages": [
        "cli", 
        "fpm"
    ]
}

TASK [debops.php : debug] ******************************************************
ok: [server] => {
    "php__base_packages": [
        "php7.0", 
        "curl", 
        "gd", 
        "mcrypt"
    ]
}

TASK [debops.php : debug] ******************************************************
ok: [server] => {
    "php__packages": []
}

TASK [debops.php : debug] ******************************************************
ok: [server] => {
    "php__group_packages": []
}

TASK [debops.php : debug] ******************************************************
ok: [server] => {
    "php__host_packages": []
}

TASK [debops.php : debug] ******************************************************
ok: [server] => {
    "php__dependent_packages": []
}

TASK [debops.php : Get available PHP packages for selected version] ************
ok: [server]

TASK [debops.php : Install PHP packages] ***************************************
failed: [server](item=[u'', u'php7.0-cli', u'php7.0-fpm', u'php7.0', u'php7.0-curl', u'php7.0-gd', u'php7.0-mcrypt']) => {"failed": true, "item": ["", "php7.0-cli", "php7.0-fpm", "php7.0", "php7.0-curl", "php7.0-gd", "php7.0-mcrypt"], "msg": "No package matching '' is available"}
`

**Comment by batthebee** [comment] 2016-10-29 22:46
Same behavior here, But when i run the playbook a second time, its working :)

`
[debops_all_hosts]
testing

[debops_service_dokuwiki]
testing
`

tested under vagrant with  "debian/jessie64" and "ubuntu/trusty64"

**Comment by drybjed** [comment] 2016-10-30 07:46
I have updated the package filter script in the `debops.php`. Unfortunately I cannot reproduce the issue on my systems... Can you get the latest `master` commit of the `debops.php` role and check if that fixes the issue?

**Comment by batthebee** [comment] 2016-10-30 11:09
`debops-update` `debops` -> same issue

**Comment by mvsantoss** [comment] 2016-10-31 16:15
Hi, I updated the debops and it's working.

**Comment by drybjed** [comment] 2016-10-31 17:41
Well, then which is it? Anybody else has this issue? I cannot reproduce this on my system, I'd like to know if it's still present or not. I'll wait with a new release a bit to confirm.

**Comment by carlalexander** [comment] 2016-12-23 13:04
I'm getting regular reports of this issue as well. I also get it on an inconsistent basis with updated debops libraries.

**Comment by carlalexander** [comment] 2016-12-23 13:17
I should point out that running the playbook a second time always fixes the issue. Only happens the first time it runs.

**Comment by balkin** [comment] 2016-12-28 06:26
For me, it's always reproducible, no matter if I run playbook for the first time, second or third. I even istalled the same packages manually, it didn't help as well. I ran it with -vvvv and this is the gist with debug output, maybe it will help to find out what's happening: https://gist.github.com/balkin/01451ed5e40c554394e8f07c337370cf

I'm not familiar with debops/ansible, but on the first glance it looks like the issue is with the `script/php-filter-packages.sh cli fpm php7.0 curl gd mcrypt mysql curl dev redis xml`. It returns

     "stdout": "\r\nphp7.0-cli\r\nphp7.0-fpm\r\nphp7.0\r\nphp7.0-curl\r\nphp7.0-gd\r\nphp7.0-mcrypt\r\nphp7.0-mysql\r\nphp7.0-curl\r\nphp7.0-dev\r\nphp-redis\r\nphp7.0-xml\r\n", 

So the first empty line is trying to be installed. Not sure if it helps or even makes things more complicated, but I tried to run the script myself using `ssh hostname /root/.local/share/debops/debops-playbooks/roles/debops.php/files/script/php-filter-packages.sh cli fpm php7.0 curl gd mcrypt mysql curl dev redis xml >//tmp/output.txt`

And the output.txt has no empty lines. Further more, it doesn't have any `\n\r` inside, lines are delimited only by LF (`\n`, 0x0a).

**Comment by carlalexander** [comment] 2017-01-07 19:58
I've been trying to troubleshoot this issue this afternoon. It's happening to me all the time now. I've tried a few solution. Thought I'd found one, but that wasn't the case. 

Here's the `-vvvv` output:

```bash
ok: [example.com] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "_raw_params": "script/php-filter-packages.sh cli fpm php7.0 curl gd mcrypt mysql curl dev redis xml"
        },
        "module_name": "script"
    },
    "rc": 0,
    "stderr": "OpenSSH_7.3p1, LibreSSL 2.4.1\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 30306\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to dev.carlalexander.ca closed.\r\n",
    "stdout": "\r\nphp7.0-cli\r\nphp7.0-fpm\r\nphp7.0-curl\r\nphp7.0-gd\r\nphp7.0-mcrypt\r\nphp7.0-mysql\r\nphp7.0-curl\r\nphp7.0-dev\r\nphp-redis\r\nphp7.0-xml\r\n",
    "stdout_lines": [
        "",
        "php7.0-cli",
        "php7.0-fpm",
        "php7.0-curl",
        "php7.0-gd",
        "php7.0-mcrypt",
        "php7.0-mysql",
        "php7.0-curl",
        "php7.0-dev",
        "php-redis",
        "php7.0-xml"
    ]
}
```

The initial `\r\n` seems to be tripping out the `stdout_lines`. Again not sure why. My bash isn't that strong so I'm not sure what's going on or if it's ansible issue.

**Comment by carlalexander** [comment] 2017-01-07 20:14
Same bug if I change the following step to this:

```yml
- name: Install PHP packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ php__register_filtered_packages.stdout.splitlines() }}'
  notify: [ 'Restart php-fpm' ]
```

**Comment by carlalexander** [comment] 2017-01-07 20:27
Actually, I think this works!

```yml
- name: Install PHP packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ php__register_filtered_packages.stdout.strip().splitlines() }}'
  notify: [ 'Restart php-fpm' ]
```

**Comment by carlalexander** [comment] 2017-01-07 20:37
This worked so far. I'll keep testing it. It's worth noting that I'm seeing some open issues about `stdout_lines` in the Ansible project that seems similar to this. So it might be a bug there.

**Comment by carlalexander** [comment] 2017-01-09 11:53
I'm submitting a patch with this fix since it seems to have worked well for me over the weekend.

**Closed as completed** 2017-01-09 12:15 UTC
